// packages/host-vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import remoteReactBtn from "./components/reactComponents.vue";

const count = ref(20);

function handleHostVueClick(value:number) {
  console.log("count",value);
  count.value = value;
}

function handleHostReactClick(value:number) {
  console.log("value",value);
}
</script>

<template>
  <div>
    <h1>Host Project in Vue</h1>
    <h3>Remote Components in Vue</h3>
    <remote-vue-btn title="host-in-vue" :count="count" @handle-click="handleHostVueClick"/>
    <h3>Remote Components in React</h3>
    <remote-react-btn title="host-in-react" :count="10" :handleClick="handleHostReactClick"/>
  </div>
</template>

<style scoped>

</style>

// packages/remote-react/src/App.tsx
import './App.css'
import Button from './components/Button'

function App() {

  const defaultHandleClick = () => {
    console.log(' default Click')
  
  }

  return (
    <>
      <h1>Remote Project in React</h1>
      <Button title={'默认数据'} handleClick={defaultHandleClick}></Button>
    </>
  )
}

export default App
